<a href="https://colab.research.google.com/github/ShepardSiegel/hotline/blob/master/Chinese_Whispers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chinese Whispers (CW) Example from Biemann Paper Figure 2

Because of the random selection of permutations and the random choice when there are ties, the result may not be the same run-to-run. In most some cases, we see ***the same 5-6 clustering*** shown in the paper's example, offen with different classes. But in some cases we do not get the expected, intuiutive results: We get a different clustering entirely, for example, all vertices of the same class.

Re-run the second code block and scroll to the bottom to (usually) see the 5-6 clustering as shown in the paper's figure 2.


In [0]:
import numpy as np
import random
from collections import Counter

In [0]:
# Zero-Origin 11x11 Adjacency Graph Matrix from Figure 2 of Biemann paper
# Each Row is node (row 0 is node 1 from the figure)
# Each non-zero Column entry is an edge...
AG = np.array([
      [0,1,1,1,1,0,0,0,0,0,1],
      [1,0,1,1,1,0,0,1,0,0,0],
      [1,1,0,1,1,0,0,0,0,0,0],
      [1,1,1,0,1,0,0,0,0,0,0],
      [1,1,1,1,0,0,0,0,0,0,0],
      [0,0,0,0,0,0,1,1,0,1,1],
      [0,0,0,0,0,1,0,0,1,1,1],
      [0,1,0,0,0,1,0,0,1,0,1],
      [0,0,0,0,0,0,1,1,0,1,1],
      [0,0,0,0,0,1,1,0,1,0,1],
      [1,0,0,0,0,1,1,1,1,1,0]])
print(AG) # Adjacency Graph matrix
classes = list(range(1,12)); print(classes) # 0-origin, class numbers are 1-origin
for j in range(3): # Run 3 iterations as in paper
    for i in np.random.permutation(len(classes)): # All vertices in permuted order
        print("j =",j," i =",i); print(classes)   # j is the iteration; i is the current vertex
        agc = [classes[k] for k in range(len(classes)) if AG[i,k] > 0]
        print("agc =",agc) # list of classes in neighborhood of current vertex (vertex i in 0-origin)
        cd = Counter(agc); print(cd)
        c = cd.most_common(); print("c =",c)
        print("ne =",c[0][1]) # number of edges of the highest rank class
        a = [c[k][0] for k in range(len(c)) if c[k][1] == c[0][1]]
        print("a =",a) # list of highest rank classes
        rc = random.choice(a); print("rc =",rc) # pick one
        classes[i] = rc # update classes list with the random choice
        print()

[[0 1 1 1 1 0 0 0 0 0 1]
 [1 0 1 1 1 0 0 1 0 0 0]
 [1 1 0 1 1 0 0 0 0 0 0]
 [1 1 1 0 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 1 1 1]
 [0 1 0 0 0 1 0 0 1 0 1]
 [0 0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 0 1 1 0 1 0 1]
 [1 0 0 0 0 1 1 1 1 1 0]]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
j = 0  i = 8
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
agc = [7, 8, 10, 11]
Counter({7: 1, 8: 1, 10: 1, 11: 1})
c = [(7, 1), (8, 1), (10, 1), (11, 1)]
ne = 1
a = [7, 8, 10, 11]
rc = 10

j = 0  i = 3
[1, 2, 3, 4, 5, 6, 7, 8, 10, 10, 11]
agc = [1, 2, 3, 5]
Counter({1: 1, 2: 1, 3: 1, 5: 1})
c = [(1, 1), (2, 1), (3, 1), (5, 1)]
ne = 1
a = [1, 2, 3, 5]
rc = 1

j = 0  i = 7
[1, 2, 3, 1, 5, 6, 7, 8, 10, 10, 11]
agc = [2, 6, 10, 11]
Counter({2: 1, 6: 1, 10: 1, 11: 1})
c = [(2, 1), (6, 1), (10, 1), (11, 1)]
ne = 1
a = [2, 6, 10, 11]
rc = 10

j = 0  i = 9
[1, 2, 3, 1, 5, 6, 7, 10, 10, 10, 11]
agc = [6, 7, 10, 11]
Counter({6: 1, 7: 1, 10: 1, 11: 1})
c = [(6, 1), (7, 1), (10, 1), (11, 1)]
ne = 1
a